title: Mijn afbeelding wordt niet weergegeven
hero_image: images/banner.png
description: Wat moet je doen als jouw afbeelding niet in HTML wordt weergegeven.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Mijn afbeelding wordt niet weergegeven
